### ISSUE TITLE
AUR PKGBUILD READY UP

### ISSUE THREAD

**Issue by FadeMind** [varlesh/Arc-Dark-KDE#1]
@varlesh 
https://aur.archlinux.org/packages/arc-dark-suite-git/

Just please add Install note to `README.md` file ;)

`yaourt -S arc-dark-suite-git`

**Comment by varlesh** [comment]
wow-wow-wow :) Big thx

**Comment by varlesh** [comment]
Maybe add optional depends - gtk-theme-arc and papirus-icon-theme-kde?

**Comment by FadeMind** [comment]
@varlesh https://aur.archlinux.org/cgit/aur.git/commit/?h=arc-dark-suite-git&id=809295c0dd873b9bcd16c34789b9b100bb484beb

See cp name magic :smiley:

**Comment by varlesh** [comment]
Fine :smile:
