### ISSUE TITLE
These colors hurt my eyes. Please fix.

### ISSUE THREAD

**Issue by indrakaw** [varlesh/Arc-Dark-KDE#10]
Screenshoot:
![screenshot_20160625_061022](https://cloud.githubusercontent.com/assets/9590878/16352744/91863f36-3a9b-11e6-9d82-8ba9dfa924f3.png)

I tried set Arc Dark as konsole's color scheme, and this is the result. Can't read yellow text on gray background. Please fix.

**Comment by codeshard** [comment]
Same issue here. All ncurses based apps(mc, moc, etc) have those annoying colors. Any idea?

**Comment by varlesh** [comment]
Like this variant?
![screenshot_20160805_175359](https://cloud.githubusercontent.com/assets/8083855/17440568/cba9c4b6-5b35-11e6-9c10-d5adb159a15f.png)

**Comment by varlesh** [comment]
Please test
[arc-dark-new.colorscheme.txt](https://github.com/varlesh/Arc-Dark-KDE/files/404012/arc-dark-new.colorscheme.txt)

**Comment by indrakaw** [comment]
Nope.
![screenshot_20160808_093318](https://cloud.githubusercontent.com/assets/9590878/17467691/3d52ca10-5d4b-11e6-8067-c4a32650e1a9.png)

**Comment by FadeMind** [comment]
@varlesh  I will take care on this ASAP.

**Comment by varlesh** [comment]
I fix yellow color 
@FadeMind you collaborator. Need fix makefile

**Comment by varlesh** [comment]
@FadeMind Please NOT update PKGBUILDs, because need test it.

**Comment by varlesh** [comment]
Makefile fixed c1ff979f703901bc7c9e20ed0e61db6a53fd29e8

**Comment by varlesh** [comment]
@FadeMind Papirus Arc icon theme available too. Makefile fixed.
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/commit/216dd04a595f11bebef89f3b6bae3d7ef7bd7a3b
All done... i think

**Comment by varlesh** [comment]
We need rename repo to **Arc-KDE** and fix new URL on PKGBUILDs

**Comment by varlesh** [comment]
or no... because some users already used this url ... i don't know how better

**Comment by FadeMind** [comment]
Lighter Arc version should have separated GH repository and curent Arc-Dark-KDE name should be stay as is.

**Comment by varlesh** [comment]
Ok

**Comment by FadeMind** [comment]
And DON'T mix this two color variants releases in one package. This is misleading.

**Comment by varlesh** [comment]
Arc moved https://github.com/varlesh/Arc-KDE

**Comment by varlesh** [comment]
Need clear makefile and del arc

**Comment by varlesh** [comment]
@FadeMind I'm finish. You collaborator on arc.
