### ISSUE TITLE
Papirus Icon Set

### ISSUE THREAD

**Issue by theGrymm** [varlesh/Arc-Dark-KDE#11]
Hi, love your work.

Some advice on the icon set however. 

I've installed papirus-pack-kde5 from your repository as per the instructions provided.

Regardless of choosing any of the papirus icon sets the folder icons displayed in Dolphin point to those in the 'symbolic' directory rather than in /places/48x48 for example.

I've attached a cropped screenshot from Dolphin.

The left pane is how my Home Directory appears, and the right pane /usr/share/icons/papirus/48x48/places which are the icons I would like to see applied to the folders.

Attempting to change the folder icon by manually selecting through properties does not work.  
![papirus](https://cloud.githubusercontent.com/assets/19159354/16355490/4b44cab4-3afb-11e6-9cd6-aa7d22d59a62.png)

Any advice you can offer would be appreciated.

**Comment by varlesh** [comment]
For Arc Dark i'm recommend use Kvantum style for Qt4 and Qt5 - it's looks better.
For Kubuntu available package here:
https://github.com/tsujan/Kvantum/releases
And themes here (also available on KDE-Look):
https://github.com/varlesh/Arc-Dark-KDE/tree/master/Kvantum

**Comment by theGrymm** [comment]
With regard to the icons.
As I understand it the side panel uses 16px icons.
Is it possible to have 16px icons on the side panel and 48px icons in the folder panel.
The look I was hoping for is the exact same look as appears in your preview.

![papirus preview](https://cloud.githubusercontent.com/assets/19159354/16356403/9b45f90c-3b19-11e6-9910-1ac0b24cd349.png)

The above image is cropped from your preview, note the difference in the icons in the side panel and the folder panel.

![papirus](https://cloud.githubusercontent.com/assets/19159354/16356406/ce81190a-3b19-11e6-882d-7dfd9c40d0dd.png)

This is how it looks on my system.

**Comment by varlesh** [comment]
I don't know why your 48px-icons use really 16px size. It's impossible, because:
```
[16x16/places]
Context=Places
Size=16
MinSize=16
MaxSize=24 - This Max size!!!
Type=Scalable

[32x32/places]
Context=Places
Size=32
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed
```

64px places maybe need as Type=Scalable MinSize=64 MaxSize=512 - BUT, this really not neede, because nobody used this  very big icons.

**Comment by varlesh** [comment]
@FadeMind You confirm this?

**Comment by FadeMind** [comment]
![image 009](https://cloud.githubusercontent.com/assets/9846948/16356515/8c83805e-3ada-11e6-9a83-fb618e20d0e3.png)
@varlesh

**Comment by theGrymm** [comment]
Hi Varlesh,

I've also been looking at the index.theme file, and comparing it to the index.theme files for icon sets that don't have this problem.

These settings are from the Papirus index.theme file

`DesktopDefault=48
ToolbarDefault=16
ToolbarSizes=16,22,24,32
MainToolbarDefault=16
MainToolbarSizes=16,22,32
PanelDefault=16
PanelSizes=22,32,48`

And these setting from the Breeze index.theme file

`DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=32
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256`

To be honest I'm not a guru at this.

But I couldn't help but notice that the Breeze index.theme uses PanelDefault=32, the Papirus index.theme uses PanelDefault=16.

Could this be what is happening.

**Comment by varlesh** [comment]
@theGrymm please show:
`cat ~/Music/.directory`

**Comment by theGrymm** [comment]
[Desktop Entry]
Icon=folder-sound

**Comment by varlesh** [comment]
It's strange, because @FadeMind not confirm this and i'm too
you delete plasma cache and apply theme again?
`rm -rf ~/.cache/{plasm*,icon*}`
Maybe you not install (or reaname) papirus icon theme, because papirus-dark and papirus-arc-dark use symlinks with papirus.
If you apply papirus icon theme (non dar and non ark-dark ) 48px places used really 16px too?

**Comment by theGrymm** [comment]
I deleted the plasma cache, then tried applying the theme again.
It didn't work.

I installed the complete papirus pack as described by the instructions on your site.

`apt-cache policy papirus-pack-kde5
papirus-pack-kde5:
  Installed: 2016.06.23
  Candidate: 2016.06.23
`

**Comment by theGrymm** [comment]
I'm baffled to mate.
I just removed / purged the papirus package from my system, cleared the plasma cache then reinstalled the papirus package again.
Unfortunately it didn't work then either.
Any way it's late here and I need some sleep.
Thank you for all your help.

**Comment by FadeMind** [comment]
Check manually folders icon for each one.

**Comment by theGrymm** [comment]
For each one that is in my folder pane?

Or run cat ~/Music/.directory for each directory, replacing Music accordingly?

**Comment by theGrymm** [comment]
Hi folks,

thought you might like to know that with the last update of the package from your repository, the icon set is displaying correctly for me now.

Thank you both for the advice and information, in trying to fix the original problem.
