### ISSUE TITLE
New icon "klipper.svgz" doesn't show

### ISSUE THREAD

**Issue by arthurflor** [varlesh/Arc-Dark-KDE#12]
I don't know why, but here, the new icon (klispper.svgz) doesn't show on the system tray.
However, the old icon works.

**Comment by varlesh** [comment]
i'm not confirm this. You delete plasma cache and apply plasma theme again?
`rm -rf ~/.cache/plasm*`

**Comment by arthurflor** [comment]
It worked!

**Comment by FadeMind** [comment]
@varlesh I'll add proper post install script for AUR packages then against this issue...

**Comment by varlesh** [comment]
thx)

**Comment by FadeMind** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=arc-dark-suite-git&id=8a4c6ed271e36e2f2fbfe08fbed13bf5062b4a2c

https://aur.archlinux.org/cgit/aur.git/commit/?h=arc-dark-suite&id=3832b9f68f99dd16fc2ed0f0795b8f638ca7bb00
