### ISSUE TITLE
color in device notifier plasma 5.7.2

### ISSUE THREAD

**Issue by rajesh-sathyamoorthy** [varlesh/Arc-Dark-KDE#14]
Hi, 

love the theme.
currently on manjaro linux on plama 5.7.2

On the device notifier, noted the color to highlight selections blends with the free space indicator and also selection for eg to open drive or download photos also is the same color (http://i.imgur.com/i0ylUC4.png) On breeze noted the main selection when highlighted is a lighter tone.

Is there a way to adjust this?

Thank you.

**Comment by varlesh** [comment]
Hi.
On Breeze use transparent highlight selection, but on Arc not transparent, also for **slider** use similar color with **viewitem** - it's Arc style and i'm don't want replace colors.

**Comment by rajesh-sathyamoorthy** [comment]
Is there a way to manually change it?

Thanks

**Comment by varlesh** [comment]
Yes. 
- Download file **viewitem.zip**
- Rename to **viewitem.svgz**
- Replace file with sudo to /usr/share/plasma/desktoptheme/Arc-Dark/widgets/viewitem.svgz
- Clear cache and apply plasma theme again:
`rm -rf ~/.cache/plasm*`
[viewitem.zip](https://github.com/varlesh/Arc-Dark-KDE/files/421585/viewitem.zip)

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/17721671/d6ee24ae-6434-11e6-9af0-69f58b49c29e.png)

**Comment by rajesh-sathyamoorthy** [comment]
thanks :)
