### ISSUE TITLE
[PULL PROPOSAL] eclipse theme 

### ISSUE THREAD

**Issue by AD2076** [varlesh/Arc-Dark-KDE#18]
Hi varlesh, I really like your theme and since I am a Java developer I themed eclipse and the editor window to perfectly (imho) fit your theme. 
Can I pull my work into extras?

**Comment by FadeMind** [comment]
@AD2076  

@varlesh is offline some time. I can review and merge Your pull. Regards

**Comment by AD2076** [comment]
@FadeMind pulled.Should I pull in gtk project too?
