### ISSUE TITLE
Default (non-dark) theme?

### ISSUE THREAD

**Issue by francoism90** [varlesh/Arc-Dark-KDE#2]
Thanks for creating this theme. :)
If you have the time, it would be great if you create a default Arc (non-dark) version.

**Comment by cryzed** [comment]
Seconded, I would really appreciate at least the color scheme for the bright Arc theme. I'm actually using the Arc Dark Transparent window decorations in combination with the bright Arc theme for GTK and the Breeze color scheme and widget style for Qt, because I don't like dark interfaces. Having colors that more closely match those of the bright Arc theme would be great.

**Comment by NicoHood** [comment]
I aggree. Its not that I dont like dark interfaces, but most programs have a lot of problem with a full dark theme, like libreoffice.

**Comment by varlesh** [comment]
Why libreoffice have problem? If you mean gradient bug on panel, but this problem can be solved.
![screenshot_20160417_135115](https://cloud.githubusercontent.com/assets/8083855/17554915/fed81fde-5f15-11e6-88b0-55d60297a58f.png)
`echo "export SAL_USE_VCLPLUGIN=gtk" >> ~/.profile`
Logout and start LO again - all looks fine:
![screenshot_20160810_161738](https://cloud.githubusercontent.com/assets/8083855/17554929/0e9827e8-5f16-11e6-967c-5ef4f1ff97a3.png)
I can't promise Arc Darker, maybe....
Temporary you van use [KArc](https://github.com/zbeptz/KArc-theme) or Papirus.

**Comment by varlesh** [comment]
![screenshot_20160810_200438](https://cloud.githubusercontent.com/assets/8083855/17562923/b23ab464-5f35-11e6-8145-ea15d78ddb10.png)

**Comment by varlesh** [comment]
Light version added

**Comment by varlesh** [comment]
Now available:
- Arc Kvantum theme
- Arc Transparent Kvantum theme
- KDE Colorscheme
- Konsole color scheme
- Arc Aurorae theme
- Arc Transparent Aurorae Theme
- Arc yakuake skin

Preview:
![screenshot_20160811_002045](https://cloud.githubusercontent.com/assets/8083855/17571650/c6aa7df2-5f59-11e6-8fc5-8fb9123fe761.png)
![screenshot_20160811_002238](https://cloud.githubusercontent.com/assets/8083855/17571660/ccc320cc-5f59-11e6-8c71-be3ea0b95e21.png)

**Comment by alexara** [comment]
> Now available:
Thank you very much!

Would you mind to make your dark theme fully fit to the official arc dark theme? :-) 
There are actually some dark elements even in the bright theme which gives some contrast overall and makes it less boring.

For instance Thunar (XFCE) has a dark bar on the left side: 

![thunar_ark_dark](https://cloud.githubusercontent.com/assets/13819719/17588591/68ff1362-5fd0-11e6-883e-61852c9346e1.png)

Alex

**Comment by varlesh** [comment]
@alexara It's impossible, because kvantum not support colorize sidebar and on Dolphin sidebar not used symbolic icons - that not really.
PS: KDE not used symbolic icons everywhere.

**Comment by varlesh** [comment]
Light version here: https://github.com/varlesh/Arc-KDE

**Comment by FadeMind** [comment]
@varlesh FYI :laughing:

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
@FadeMind need update PKGBUILD icon theme  (for arc kde)

**Comment by FadeMind** [comment]
@varlesh 
https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-icon-theme-kde&id=74ac73c4ca36961ec9581550b62ec9afaa0fd39a

https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-icon-theme-kde-git&id=d373829fbc78b4ebc0e879df1c8c5012545b063a
