### ISSUE TITLE
No icons on context menu

### ISSUE THREAD

**Issue by malimM** [varlesh/Arc-Dark-KDE#21]
Hi there, when I select Kvantum under: Application Style -> Widget Style, icons don't show up in context menus
Icon:
![icon](https://cloud.githubusercontent.com/assets/10934574/19634184/08a4c9d0-99b9-11e6-99ef-b6c9a7acf38d.jpg)
No icons:
![no icon](https://cloud.githubusercontent.com/assets/10934574/19634186/093b50b2-99b9-11e6-9050-429d8668c482.jpg)

Kvantum settings have Arc selected.

**Comment by varlesh** [comment]
It's Gnome style!
`sed -i 's|iconless_menu=true|iconless_menu=false|g' ~/.config/Kvantum/ArcDarkTransparent/ArcDarkTransparent.kvconfig`

**Comment by varlesh** [comment]
Also available on kvantummanager
![image](https://cloud.githubusercontent.com/assets/8083855/19723776/7e3e9e64-9b85-11e6-89b6-fd9090c00aa5.png)
