### ISSUE TITLE
battery icon not showing up in panel

### ISSUE THREAD

**Issue by rudevdr** [varlesh/Arc-Dark-KDE#22]
freshly installed kde on ubuntu and install theme from repository. now facing issue that battery icon for brightness and battery info not appearing, creating blank space when clicked toggles the said info box.

![screenshot_20161101_190451](https://cloud.githubusercontent.com/assets/19689713/19891582/c6408ca0-a066-11e6-9e52-09d4d03d4bbd.png)

after klipboard you can see blank space 

hoping to reply quickly

**Comment by varlesh** [comment]
```
rm -rf ~/.cache{plasm*,ico*}
killall plasmashell
```
**ALT+F2**:
`plasmashell`
**ENTER**

**Comment by rudevdr** [comment]
followed your steps still not successful. Icon is still not showing up.

**Comment by varlesh** [comment]
Delete cache, kill plasmashell and reapply plasma theme again.
i'm not confirm this:
![image](https://cloud.githubusercontent.com/assets/8083855/19892053/fc17581c-a053-11e6-9841-c6c1122d5251.png)

**Comment by rudevdr** [comment]
closed by mistake sorry

**Comment by varlesh** [comment]
battery icon  updated on new version see #17. You must delete plasma cache.

**Comment by varlesh** [comment]
`rm -rf ~/.cache/{plasm*,ico*}`
 - LogOut on System
- Apply again plasma theme

**Comment by rudevdr** [comment]
so how i am i supposed to update from repository or manually

**Comment by varlesh** [comment]
On PPA for 14.04 and 16.04 already available fresh git-version.

**Comment by varlesh** [comment]
@rudevdr On Plasma 5.7 bug reproduced. I fixed this soon.

**Comment by rudevdr** [comment]
agreed

**Comment by varlesh** [comment]
Fixed. Soon will be available  on kde-look and PPA

**Comment by varlesh** [comment]
@rudevdr PPA updated
