### ISSUE TITLE
Transparency doesn't work in KDE Neon 5.8.3

### ISSUE THREAD

**Issue by aronzillo** [varlesh/Arc-Dark-KDE#23]
I did all instructions but transparency doesn't work in KDE Neon 5.8.3 looks awful, why?
(Would be problem of Kvantum?)

![screenshot_20161104_004827](https://cloud.githubusercontent.com/assets/12212275/19996928/a2e552b8-a228-11e6-9f1f-e500537d73de.png)

**Comment by varlesh** [comment]
it's default kvantum theme. Open kvantummanager and select **Arc Dark Transparent**
![image](https://cloud.githubusercontent.com/assets/8083855/19998672/36a82772-a27f-11e6-86a7-0e48a8e1e01a.png)

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/19998707/58386690-a27f-11e6-9a44-e37474e4685a.png)
