### ISSUE TITLE
Error makefile : QtCurve directory doesn't exist

### ISSUE THREAD

**Issue by fggarcia** [varlesh/Arc-Dark-KDE#6]
cp: no se puede efectuar `stat' sobre 'QtCurve/Arc Dark.qtcurve': No existe el fichero o el directorio
Makefile:25: fallo en las instrucciones para el objetivo 'local'

Makefile make reference to this folder ("QtCurve") that not exist anymore.

**Comment by varlesh** [comment]
Sorry about that i fix this (available on arc-dark-suite-git) QtCurve discontinue, please use Kvantum.
@FadeMind Please fix PKGBUILD's:
- need remove QtCurve from optdepends
- also better moved kvantum from optdepends to depends (because that better style for Arc Dark KDE)
- and merge arc-dark-kde makefile with kvantum makefile

**Comment by FadeMind** [comment]
FIxed in https://github.com/varlesh/Arc-Dark-KDE/pull/7

**Comment by varlesh** [comment]
@FadeMind Need delete qtcurve form papirus too and fix makefile and PKGBUILDs

**Comment by varlesh** [comment]
I dele PapirusDevelopmentTeam/papirus-qtcurve-theme

**Comment by FadeMind** [comment]
Removing `papirus-qtcurve-theme{-git}` from PKGBUILD
https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=7500e022c319a514807844f949ea125b0ff20a21

and

https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus&id=06d6bae0357068d6b42b40dc1ba9c674393e9dec

Makefile change is not needed. I commited request removing `papirus-qtcurve-theme` and `papirus-qtcurve-theme-git` from AUR.

papirus meta packages does not have any file itself (only depends rules in PKGBUILD code).

@varlesh

**Comment by varlesh** [comment]
@FadeMind papirus-qtcurve-theme and papirus-qtcurve-theme-git wil be remove from AUR, because QtCurve discontinue and repository not available anymore.
