### ISSUE TITLE
close button on windows overview

### ISSUE THREAD

**Issue by arshavindn** [varlesh/Arc-Dark-KDE#8]
the close button next to cursor is not aligned
![screenshot_20160617_234814](https://cloud.githubusercontent.com/assets/10246162/16158698/a4c9283c-34e8-11e6-83f0-a3dde177b598.png)

**Comment by varlesh** [comment]
Maybe this plasma bug?
Because icon centered:
![screenshot_20160617_201448](https://cloud.githubusercontent.com/assets/8083855/16158880/40879716-34c8-11e6-922f-c2cc851048a3.png)

**Comment by varlesh** [comment]
oops.. this icon use from icon theme, not plasma.
This plasma bug, because reproduced on Breeze icon and Breeze plasma theme
![screenshot_20160617_203009](https://cloud.githubusercontent.com/assets/8083855/16159243/4e80ccdc-34ca-11e6-923e-544306975103.png)

**Comment by arshavindn** [comment]
thanks for figuring it out
