### ISSUE TITLE
Border size

### ISSUE THREAD

**Issue by Svadkos** [varlesh/Arc-Dark-KDE#9]
Setting anything other than "normal" isn't work as it should.
Also, in Breeze if choose option "no border" than in the corner appear area which can stretch the window.

**Comment by varlesh** [comment]
Breeze - this QML decoration. Arc Dark - thi SVG. If you don't like Arc Dark use Breeze.

**Comment by Svadkos** [comment]
Well, here https://github.com/zbeptz/KArc-theme/tree/master/KArc-Dark it sort of works, even if there no visible corner. 
Not ideal, but at least something.

**Comment by varlesh** [comment]
@Svadkos I'm reduced size borders.

**Comment by Svadkos** [comment]
Thanks.
